name: flutter_prunekit
description: Ship leaner Dart & Flutter apps by removing unused classes, methods, and variables.
version: 2.1.1
homepage: https://github.com/furkanvatandas/flutter_prunekit
repository: https://github.com/furkanvatandas/flutter_prunekit
issue_tracker: https://github.com/furkanvatandas/flutter_prunekit/issues
documentation: https://github.com/furkanvatandas/flutter_prunekit#readme

topics:
  - dart
  - flutter
  - static-analysis
  - dead-code
  - code-quality

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^8.1.1
  ansi_styles: ^0.3.2+1
  args: ^2.7.0
  glob: ^2.1.3
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  test: ^1.26.3
  lints: ^6.0.0

executables:
  flutter_prunekit: